;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Level.Door.Door0",DevComment="")
+GameplayTagList=(Tag="Level.Door.Door1",DevComment="")
+GameplayTagList=(Tag="Level.Key.Key0",DevComment="")
+GameplayTagList=(Tag="Level.Key.Key1",DevComment="")
+GameplayTagList=(Tag="Level.Key.Keys",DevComment="")
+GameplayTagList=(Tag="Level.Test",DevComment="")
+GameplayTagList=(Tag="Player.Keys",DevComment="")
+GameplayTagList=(Tag="Player.LevelIndex",DevComment="")

